server:
  port: 8087
spring:
  config:
    activate:
      on-profile: default
  application:
    name: ausenciasAceptadas
  datasource:
    url: jdbc:mysql://${ausenciasAceptadas-db:localhost}:${production-port:3312}/ausenciasAceptadas
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher