server:
  port: 8086
spring:
  config:
    activate:
      on-profile: default
  application:
    name: ausenciasSolicitadas
  datasource:
    url: jdbc:mysql://${ausencias-solicitadas-db:localhost}:${production-port:3311}/ausencias-solicitadas
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

