server:
  port: 8082

spring:
  application:
    name: vestuarios
    data:
      mongodb:
        host: localhost
        database: vestuarios
        username: user
        password: password
        port: 27017
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
