server:
  port: 8082

spring:
  application:
    name: vestuarios
    data:
      mongodb:
        host: localhost
        database: vestuarios
        user: root
        password: password
        uri: http://host:27017/vestuarios
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
