server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  application:
    name: vestuarios
    data:
      mongodb:
        host: localhost
        database: vestuarios
        user: root
        password: password
        port: 27017
    jpa:
      hibernate:
        ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
