server:
  port: 8082

spring:
  application:
    name: vestuarios
    data:
      mongodb:
        host: localhost
        database: vestuarios
        username: user
        password: password
        uri: mongodb://host:27017/vestuarios
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
